apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hydradx-api-app
  labels:
    cloud.googleapis.com/location: europe-west3

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "30"
        run.googleapis.com/vpc-access-connector: hydradx-api-connector

    spec:
      timeoutSeconds: "60"
      containers:
        - image: europe-west3-docker.pkg.dev/rich-principle-383410/hydradx-api/hydradx-api-app:latest
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
