apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: cache-coingecko-tickers-job
  labels:
    cloud.googleapis.com/location: europe-west3

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: hydradx-api-connector
    spec:
      parallelism: 0
      template:
        spec:
          maxRetries: "0"
          timeoutSeconds: "300"
          containers:
            - image: europe-west3-docker.pkg.dev/rich-principle-383410/hydradx-api/hydradx-api-jobs:latest
              env:
                - name: JOB_NAME
                  value: cache-coingecko-tickers-job
                - name: GOOGLE_CLOUD_RUN_JOB
                  value: "true"
                - name: PGPASSWORD_DB_ORCA
                  valueFrom:
                    secretKeyRef:
                      key: "latest"
                      name: PGPASSWORD_DB_ORCA
              resources:
                limits:
                  cpu: "1"
                  memory: 512Mi
